version: '3'
services:
  hash-brownie:
    restart: always
    build: .
    ports:
      - "443:4000"
    volumes:
      - .:/www
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "5"
    deploy:
     restart_policy:
       condition: on-failure

  redis:
    image: "redis:3.2.8-alpine"
